// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roasting_outtake.proto

package backend.test.coffee_roasting.grpc.roasting_outtake;

public interface RoastingOuttakeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoastingOuttakeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string grain_type = 1;</code>
   * @return The grainType.
   */
  java.lang.String getGrainType();
  /**
   * <code>string grain_type = 1;</code>
   * @return The bytes for grainType.
   */
  com.google.protobuf.ByteString
      getGrainTypeBytes();

  /**
   * <code>string origin_country = 2;</code>
   * @return The originCountry.
   */
  java.lang.String getOriginCountry();
  /**
   * <code>string origin_country = 2;</code>
   * @return The bytes for originCountry.
   */
  com.google.protobuf.ByteString
      getOriginCountryBytes();

  /**
   * <code>double input_weight_grams = 3;</code>
   * @return The inputWeightGrams.
   */
  double getInputWeightGrams();

  /**
   * <code>double output_weight_grams = 4;</code>
   * @return The outputWeightGrams.
   */
  double getOutputWeightGrams();

  /**
   * <code>string brigade_id = 5;</code>
   * @return The brigadeId.
   */
  java.lang.String getBrigadeId();
  /**
   * <code>string brigade_id = 5;</code>
   * @return The bytes for brigadeId.
   */
  com.google.protobuf.ByteString
      getBrigadeIdBytes();
}
