// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roasting_outtake.proto

package backend.test.coffee_roasting.grpc.roasting_outtake;

public interface RoastingOuttakeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoastingOuttakeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
